import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar, Layout, Footer } from "@/shared/components";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JakToSwim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Navbar />
        </Layout>

        {children}

        <Layout className="max-w-screen w-full bg-black rounded-tl-2xl rounded-tr-2xl py-12">
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
